services:
  db_pg:
    image: postgres:13
    environment:
      POSTGRES_USER: payment_db_user
      POSTGRES_PASSWORD: payment_db_password
      POSTGRES_DB: payment_db_test
    healthcheck:
      test: pg_isready -U payment_db_user -d payment_db_test
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 30s
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  payment_microservice:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: payment_db_user
      POSTGRES_PASSWORD: payment_db_password
      POSTGRES_DB: payment_db_test
      POSTGRES_SERVER: db_pg
    ports:
      - 8004:8004
    volumes:
      - .:/payment_microservice
    depends_on:
      db_pg:
        condition: service_healthy

volumes:
  pg_data:
    driver: local
